### PR TITLE
add Dukes/MacDonald

### PR DESCRIPTION
**Pull request by MatthewCaseres**

### CODE REVIEW

**Comment by MatthewCaseres** [comment]
closes https://github.com/JuliaActuary/MortalityTables.jl/issues/127

**Review by alecloudenback — CHANGES_REQUESTED** [review]
Looks good overall, a couple of things before merging:

- Needs docstrings
- Please remove the type annotations on the methods. 
   - Restricting to Float64 prevents other rate types (e.g. Float32, or [Duals](https://juliadiff.org/ForwardDiff.jl/stable/dev/how_it_works/#Dual-Number-Implementation) used with automatic differentiation)
   - errors can be more local to where the inappropriate type is used

**Comment by MatthewCaseres** [comment]
should be ok now

**Comment by alecloudenback** [comment]
Thanks!

**Pull request merged**
